name: 'Run App Andrew Wiebe'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: windows-latest  # ✅ Switch from 'ubuntu-latest' to 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # ✅ Keep this for .NET 8
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1  # ✅ Install MSBuild on Windows
      - name: Restore dependencies
        run: nuget restore GithubActions.sln  # ✅ Works on Windows
      - name: Build
        run: msbuild /p:Configuration=Release GithubActions.sln  # ✅ Works on Windows
      - name: Run Unit Tests
        run: |
            & "C:\Program Files\NUnit.org\nunit-console\nunit3-console.exe" ./Tests/bin/Release/Tests.dll

